#!/bin/bash
set -e
#Create a file to store version
if [ ! -d packages ]; then
    mkdir packages
fi

printf "Creating R script...\n"

basedir=$(dirname $0)

if python3  ${basedir}/parser.py; then
    printf "Script created! Running script...\n"
else
    printf "There was an error parsing r-package.json.\nIs it correctly formatted?\n"
fi

if [ -f .Rprofile ]; then
    sed -i".bak" '/libPaths/d'  .Rprofile
fi

if Rscript install_dependencies.R; then
    printf "Script executed succesfully!\n"
else
    printf "There was an error installing the dependencies. Please, check the console output\n"
    exit 5
fi

if [ ! -f .Rprofile ]; then
    touch .Rprofile
fi

echo ".libPaths('./packages/')" >> .Rprofile 
